CREATE TABLE IF NOT EXISTS lessons (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id TEXT NOT NULL,
weekday INTEGER NOT NULL CHECK(weekday BETWEEN 0 AND 6),
subject TEXT NOT NULL CHECK(length(subject) BETWEEN 1 AND 120),
starts_at TEXT NOT NULL,
ends_at TEXT NOT NULL,
room TEXT NOT NULL DEFAULT '',
location TEXT NOT NULL DEFAULT '',
teacher TEXT NOT NULL DEFAULT '',
lesson_type TEXT NOT NULL DEFAULT '',
group_name TEXT NOT NULL DEFAULT '',
notes TEXT NOT NULL DEFAULT '',
CHECK(starts_at < ends_at)
);

CREATE TABLE IF NOT EXISTS deadlines (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id TEXT NOT NULL,
title TEXT NOT NULL CHECK(length(title) BETWEEN 1 AND 160),
subject TEXT NOT NULL DEFAULT '',
due_at TEXT NOT NULL,
description TEXT NOT NULL DEFAULT '',
source TEXT NOT NULL DEFAULT 'manual',
completed INTEGER NOT NULL DEFAULT 0 CHECK(completed IN (0, 1)),
created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::text)
);

CREATE TABLE IF NOT EXISTS preferences (
user_id TEXT PRIMARY KEY,
theme TEXT NOT NULL DEFAULT 'light' CHECK(theme IN ('light', 'dark')),
schedule_view TEXT NOT NULL DEFAULT 'week' CHECK(schedule_view IN ('week', 'day')),
mobile_schedule_view TEXT NOT NULL DEFAULT 'day'
CHECK(mobile_schedule_view IN ('week', 'day')),
visible_fields TEXT NOT NULL DEFAULT 'room,teacher,lesson_type'
);

CREATE TABLE IF NOT EXISTS users (
id TEXT PRIMARY KEY,
display_name TEXT NOT NULL DEFAULT '',
role TEXT NOT NULL DEFAULT 'user' CHECK(role IN ('user', 'admin')),
created_at TEXT NOT NULL,
last_seen_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
token_hash TEXT PRIMARY KEY,
user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
csrf_token TEXT NOT NULL,
created_at TEXT NOT NULL,
expires_at TEXT NOT NULL,
revoked_at TEXT
);

CREATE TABLE IF NOT EXISTS app_meta (
key TEXT PRIMARY KEY,
value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS external_identities (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
provider TEXT NOT NULL,
provider_user_id TEXT NOT NULL,
user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
username TEXT NOT NULL DEFAULT '',
display_name TEXT NOT NULL DEFAULT '',
linked_at TEXT NOT NULL,
UNIQUE(provider, provider_user_id),
UNIQUE(provider, user_id)
);

CREATE TABLE IF NOT EXISTS telegram_auth_replays (
replay_key TEXT PRIMARY KEY,
used_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ai_entitlements (
user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
balance INTEGER NOT NULL DEFAULT 0 CHECK(balance >= 0),
unlimited INTEGER NOT NULL DEFAULT 0 CHECK(unlimited IN (0, 1)),
free_trial_available INTEGER NOT NULL DEFAULT 1
CHECK(free_trial_available IN (0, 1)),
source TEXT NOT NULL DEFAULT 'core',
created_at TEXT NOT NULL,
updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ai_credit_reservations (
request_id TEXT PRIMARY KEY,
user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
status TEXT NOT NULL CHECK(status IN ('reserved', 'committed', 'released')),
charged INTEGER NOT NULL CHECK(charged IN (0, 1)),
amount INTEGER NOT NULL DEFAULT 1 CHECK(amount >= 0),
entitlement_source TEXT NOT NULL DEFAULT 'paid',
input_tokens INTEGER NOT NULL DEFAULT 0 CHECK(input_tokens >= 0),
output_tokens INTEGER NOT NULL DEFAULT 0 CHECK(output_tokens >= 0),
created_at TEXT NOT NULL,
updated_at TEXT NOT NULL,
committed_at TEXT,
released_at TEXT
);

CREATE TABLE IF NOT EXISTS telegram_star_payments (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
provider TEXT NOT NULL DEFAULT 'telegram_stars'
CHECK(provider='telegram_stars'),
telegram_payment_charge_id TEXT NOT NULL UNIQUE,
telegram_user_id TEXT NOT NULL,
user_id TEXT NOT NULL REFERENCES users(id),
product_id TEXT NOT NULL,
stars_paid INTEGER NOT NULL CHECK(stars_paid > 0),
credits_granted INTEGER NOT NULL CHECK(credits_granted > 0),
created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS bridge_replays (
nonce TEXT PRIMARY KEY,
used_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS product_events (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
event_name TEXT NOT NULL,
source TEXT NOT NULL DEFAULT '',
created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS feedback (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
kind TEXT NOT NULL CHECK(kind IN ('product', 'student-ai')),
rating TEXT NOT NULL DEFAULT '' CHECK(rating IN ('', 'positive', 'negative')),
message TEXT NOT NULL DEFAULT '',
request_id TEXT NOT NULL,
created_at TEXT NOT NULL,
UNIQUE(user_id, kind, request_id)
);

CREATE TABLE IF NOT EXISTS admin_actions (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
request_id TEXT NOT NULL UNIQUE,
actor_user_id TEXT NOT NULL REFERENCES users(id),
action TEXT NOT NULL,
target_user_id TEXT REFERENCES users(id),
details TEXT NOT NULL DEFAULT '',
reason TEXT NOT NULL,
result TEXT NOT NULL,
created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_lessons_user_day
ON lessons(user_id, weekday, starts_at);
CREATE INDEX IF NOT EXISTS idx_deadlines_user_due
ON deadlines(user_id, due_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_deadlines_deduplicate
ON deadlines(user_id, title, due_at, source);
CREATE INDEX IF NOT EXISTS idx_sessions_user
ON sessions(user_id, expires_at);
CREATE INDEX IF NOT EXISTS idx_product_events_name_created
ON product_events(event_name, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_product_events_deadline_once
ON product_events(user_id, event_name, source)
WHERE event_name='deadline_created';
CREATE INDEX IF NOT EXISTS idx_feedback_created
ON feedback(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_admin_actions_created
ON admin_actions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_star_payments_user_created
ON telegram_star_payments(user_id, created_at DESC);

CREATE TABLE telegram_login_attempts (
state_hash TEXT PRIMARY KEY, browser_hash TEXT NOT NULL, verifier TEXT NOT NULL,
expires_at BIGINT NOT NULL, session_hash TEXT NOT NULL, target_user_id TEXT);
CREATE TABLE restore_previews (
id TEXT PRIMARY KEY, user_id TEXT NOT NULL, file_hash TEXT NOT NULL,
state_hash TEXT NOT NULL, expires_at BIGINT NOT NULL, consumed INTEGER NOT NULL DEFAULT 0);
CREATE TABLE photo_quotes (
id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id),
image_hash TEXT NOT NULL, source TEXT NOT NULL, amount INTEGER NOT NULL,
expires_at BIGINT NOT NULL, claimed INTEGER NOT NULL DEFAULT 0);
CREATE TABLE photo_sessions (
id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id),
tasks TEXT NOT NULL, expires_at BIGINT NOT NULL);
CREATE INDEX photo_sessions_owner ON photo_sessions(user_id,expires_at);
CREATE TABLE photo_requests (
id TEXT PRIMARY KEY, session_id TEXT NOT NULL, user_id TEXT NOT NULL,
status TEXT NOT NULL, input_tokens INTEGER NOT NULL DEFAULT 0,
output_tokens INTEGER NOT NULL DEFAULT 0, created_at BIGINT NOT NULL);
CREATE INDEX restore_previews_expiry ON restore_previews(expires_at);
CREATE INDEX photo_quotes_expiry ON photo_quotes(expires_at);
CREATE INDEX photo_requests_owner_time ON photo_requests(user_id,created_at);
CREATE INDEX telegram_login_expiry ON telegram_login_attempts(expires_at);
